{{ if .Values.ingress.enabled}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.tls.secretName }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tlsSecrets.certificate | b64enc }}
  tls.key: {{ .Values.tlsSecrets.key | b64enc }}
{{- end}}