# Default values for jenkins.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

jenkins4team:
  name: devopsday

image:
  initcontainer:
    name: permissionsfix
    tag: alpine:latest
  jenkins:
    name: jenkins
    tag: jenkins/jenkins:lts
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port1:
    name: web
    value: 8080
  port2:
    name: agent
    value: 50000

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  path: /
  hosts:
    name: []
  tls:
      secretName: jenkins-tls
      hosts: []


env:
  jenkins:
    JENKINS_OPTS: --prefix=/jenkins/
    JAVA_OPTS: "-Xbootclasspath/p:lib/alpn/alpn-boot-8.1.7.v20160121.jar  -Xmx$(LIMITS_MEMORY)m -XshowSettings:vm -Dhudson.slaves.NodeProvisioner.initialDelay=0 -Dhudson.slaves.NodeProvisioner.MARGIN=50 -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85 -Duser.timezone=Asia/Shanghai"

volume:
  name: jenkins-home
  subpath: jenkins
  mountPath: /var/jenkins_home


resources:
  requests:
    cpu: "1000m"
    memory: "2048Mi"
  limits:
    cpu: "2000m"
    memory: "4096Mi"

resourceLimit:
    divisor: 1Mi



persistentVolume:
  enabled: true
  accessMode: ReadWriteMany
  size: 10G
  sc: storageclass

rbac:
  enabled: true
  roleBindKind: ClusterRoleBinding
  roleKind: ClusterRole
  rolename: cluster-admin


tlsSecrets:
  name: jenkins-tls
  certificate: |
    -----BEGIN CERTIFICATE-----
    /* Please help to input your cert file */
    -----END CERTIFICATE-----
  key: |
    -----BEGIN PRIVATE KEY-----
   /* Please help to input your private key */
    -----END PRIVATE KEY-----
